version: "3"

services:

  redis:
    image: redis
    ports:
      - 6379:6379
  database:
    image: mysql
    container_name: database_system_b
    restart: always
    ports:
      - 3309:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: system_b

