version: "3"

services:
  database:
    image: mysql
    container_name: database
    restart: always
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: auth

