version: "3"

services:

  redis:
    image: redis
    ports:
      - 6379:6379

  database:
    image: mongo
    container_name: database_system_c
    restart: always
    ports:
      - 27017:27017

  database1:
    image: mysql
    container_name: database_system_b
    restart: always
    ports:
      - 3309:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: system_b

  database2:
    image: mysql
    container_name: database_system_a
    restart: always
    ports:
      - 3308:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: system_a
    
  database3:
    image: mysql
    container_name: database
    restart: always
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: auth