version: "3"

services:
  database:
    image: mysql
    container_name: database_system_a
    restart: always
    ports:
      - 3308:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: system_a

